### ISSUE TITLE
Please tell users to use z3 4.8.8 and older

### ISSUE THREAD

**Issue by safinaskar** [xldenis/creusot#656] opened 2022-11-24 05:52 UTC
Consider this code:
```rust
#[cfg(my_prover)]
extern crate creusot_contracts;

#[cfg(my_prover)]
use creusot_contracts::*;

#[trusted]
#[ensures(result == forall<k: usize> (@a).len() - @i - 1 <= @k && @k < (@a).len() - 1 ==> (@a)[@k] <= (@a)[@k + 1])]
fn f(a: &[i32], i: usize) -> bool {
    return true;
}

fn sort(a: &mut [i32]) {
    let len = a.len();
    if a.len() == 0 {
        return;
    }
    let mut i = 0;
    #[cfg_attr(my_prover, invariant(a, (@a).len() == @len))]
    #[cfg_attr(my_prover, invariant(a, @i > 0 ==> forall<k: usize> @k < @len - @i ==> (@a)[@k] <= (@a)[@len - @i]))]
    while i < a.len() - 1 {
        if !f(a, i) {
            return;
        }
        proof_assert!(forall<k: usize> (@a).len() - @i - 1 <= @k && @k < (@a).len() - 1 ==> (@a)[@k] <= (@a)[@k + 1]);
        proof_assert!(forall<k: usize> (@a).len() - @i <= @k && @k < (@a).len() - 1 ==> (@a)[@k] <= (@a)[@k + 1]);
        proof_assert!(@i > 0 ==> forall<k: usize> @k < @len - @i ==> (@a)[@k] <= (@a)[@len - @i]);
        {
            let mut j = 0;
            let x = if i == 0 { 0 } else { a[len - i] };
            #[cfg_attr(my_prover, invariant(a, (@a).len() == @len))]
            #[cfg_attr(my_prover, invariant(a, forall<k: usize> @k < @j ==> (@a)[@k] <= (@a)[@j]))]
            #[cfg_attr(my_prover, invariant(a, @j <= @len - @i - 1))]
            #[cfg_attr(my_prover, invariant(a, forall<k: usize> (@a).len() - @i <= @k && @k < (@a).len() - 1 ==> (@a)[@k] <= (@a)[@k + 1]))]
            while j < a.len() - i - 1 {
                if a[j] > a[j + 1] {
                    let sw = a[j];
                    a[j] = a[j + 1];
                    a[j + 1] = sw;
                }
                j += 1;
            }
        }
        proof_assert!(forall<k: usize> (@a).len() - @i <= @k && @k < (@a).len() - 1 ==> (@a)[@k] <= (@a)[@k + 1]);
        proof_assert!(forall<k: usize> @k < @len - @i - 1 ==> (@a)[@k] <= (@a)[@len - @i - 1]);
        i += 1;
    }
}

fn main(){ }
```

This is my (incomplete) attempt to prove bubble sort in Creusot. I'm sorry for `my_prover` noise, I added it to make sure the source can be built in the same time by Creusot and normal rust compiler.

I check this code using Creusot (obviously, I add `--cfg my_prover` to creusot-rustc invocation). And checking takes 8.13s (I have to pass `-t` option to why3 to make sure I will not get timeout).

My z3 version is 4.8.10. This reminds me z3 regression I recently discovered when working with Prusti ( https://github.com/viperproject/prusti-dev/issues/1245 , https://github.com/viperproject/silicon/issues/664#issuecomment-1324811845 ). So I tried to use older z3 version, namely this: https://github.com/Z3Prover/z3/commit/3c9ada54b64e5516e0cf869c5de7881686df8fd0 . (This is "last good" commit I discovered when I did gitbisecting when working with Prusti).

And now that Creusot source checks for 0.42s!

So it seems that z3 regression applies to Creusot, too. Please, update installation instructions, tell your users to always use z3 no later than 4.8.8 version. See also https://twitter.com/RanjitJhala/status/1391486845435871233 .

P. S. In this code I used function `f` as "assume". Is there proper way to do "assume"?

**Comment by jhjourdan** [comment] 2022-11-24 08:20
> I'm sorry for my_prover noise, I added it to make sure the source can be built in the same time by Creusot and normal rust compiler.

That should not be necessary. Creusot attributes should allow compilation through rustc, with the "contract" feature disabled. If you have problems with that, then this is a bug.

> I check this code using Creusot (obviously, I add --cfg my_prover to creusot-rustc invocation). And checking takes 8.13s (I have to pass -t option to why3 to make sure I will not get timeout).

Is Z3 the only prover you tried? Perhaps opening Why3 IDE and using one of the automated strategies (with CVC4/5 and lat-ergo enabled) would lead to much better timing.

> So it seems that z3 regression applies to Creusot, too. Please, update installation instructions, tell your users to always use z3 no later than 4.8.8 version. See also https://twitter.com/RanjitJhala/status/1391486845435871233 .

The problem is that recent versions of Z3 also brings other improvements, so I prefer let user choose the version they want.

Has this regression been submitted as a bug report to Z3 ? I would prefer waiting for a recent version which both include the recent features and a fix for this regression.

> P. S. In this code I used function f as "assume". Is there proper way to do "assume"?

That's clearly a missing feature of Creusot. We need to add it.

**Comment by xldenis** [comment] 2022-11-24 09:30
How are you using Creusot? Your issue makes me think you are calling `why3 prove` directly, which is _not_ the intended way to use Creusot or Why3, it really must be used interactively with the IDE to gain the full potential.

Additionally, I've loaded your example in Creusot, and the whole proof passes using z3 4.11.0 in 0.11s, additionally, I strongly encourage you to use more than just Z3, you can even use multiple versions of Z3 simultaneously if you prefer.

**Comment by safinaskar** [comment] 2022-11-25 08:18
@xldenis
> How are you using Creusot?

When I need to install something, I usually install it do docker, because I don't want to pollute my main system. So I wrote Dockerfile, here it is: https://github.com/xldenis/creusot/issues/283 . I wrote it using instructions, which was present in Creusot's README in that time, i. e. at February. Now it seems that that Dockerfile doesn't work, so I slightly modified it, here is current version: https://paste.debian.net/1261802/ .

Now for unknown reasons installing opam's package `why3-ide` doesn't work, so I commented `why3-ide` in the Dockerfile.

When I need to check file, I do this:
```bash
~/opt/creusot/mlcfg ~/creusot/a.rs && time -p why3 --debug=ignore_unused_vars prove -t 20 -L ~/opt/creusot/prelude -P z3 ~/opt/creusot/a-rlib.mlcfg
```

Also, `~/opt/creusot/mlcfg` is manually modified: I added `--cfg my_prover`.

Okey, it seems that README is changed since February, so now I will try to reinstall everything (i. e. to rewrite Dockerfile and way how I check files) using modern instructions. (I hope this time I will properly install `why3-ide` package.) I will write here when I done. I will also try z3 4.11.0.

It would be very nice, if creusot include official Dockerfile.

Also, creusot's README doesn't say much about how exactly why3 IDE works. Is it GUI app? If yes, I need to properly redirect X11 connection from docker (this requires additional setup). Does using why3 IDE requires knowing why3 language?

Creusot's README give many various bash commands. Which of this commands starts GUI app? (I need to know this to redirect X11.) Please, write this in README

**Comment by safinaskar** [comment] 2022-11-25 08:42
README contains this:

> cargo install --path creusot

It seems you mean `cargo install --path REPO`

**Comment by xldenis** [comment] 2022-11-25 08:50
Yes the IDE is a GTK gui app, you can use the `./ide` script to launch it on an mlcfg file.

You won't need to know the why3 language to use the IDE unless you want to start doing advanced things, and the ide will show you your proofs with spans, so you can see in the rust code which parts are failing to prove.

**Comment by safinaskar** [comment] 2022-11-25 10:17
I'm continuing installing creusot proper way.

> It seems you mean `cargo install --path REPO`

Oops, it seems `cargo install --path REPO/creusot` should be.

Also, I tried `cargo install --path REPO/creusot` and this command failed with lots of compilation messages. Then I switched rust version to specified in `rust-toolchain` file and now everything works. So, please, tell users to use `rust-toolchain` file to build creusot

**Comment by safinaskar** [comment] 2022-11-25 11:56
Okey, it seems this time I figured everything. It seems that `cargo install --path=/some/really/long/path/to/creusot` will not work. Because it will not pick up `rust-toolchain` file. (Just now I reported this to rustup developers as https://github.com/rust-lang/rustup/issues/3115 .)

So, user should explicitly `cd` to this repo and then run `cargo install --path=...`. So, please tell the users this:

> This project uses custom `rust-toolchain` file, so it should be installed with special care. Simply typing `cargo install --path=...` will not work. You should `cd` to this repo first. Either of these two commands will work. Everything else will not
> `cd REPO && cargo install --path=creusot`
> `cd REPO/creusot && cargo install --path=.`

(Also, if you want, I can report every found issue as a separate bug report.)

**Comment by safinaskar** [comment] 2022-11-25 17:35
Okey, so I rewrote my Dockerfile. Everything now works, including X11 redirection and hence Why3 IDE

> That should not be necessary. Creusot attributes should allow compilation through rustc, with the "contract" feature disabled

Yes, now it works

> Is Z3 the only prover you tried?

Yes

> Your issue makes me think you are calling `why3 prove` directly

Okey, so now I am able to run Why3 IDE and press "0" (or "3"). But this is the only thing I know how to do in Why3 IDE and I don't want to learn any more. Because I want to use creusot in fully automatic mode. I want to author some program, check it using creusot, then make a small change, then run creusot again (in fully automatic mode!) and verify that the program still checks. So, yes, I'm using `why3 prove`.

> and the whole proof passes using z3 4.11.0 in 0.11s

Okey, so I checked my example using z3 4.11.0. And yes, it checks instantly. So, yes, original bug is resolved

**Comment by safinaskar** [comment] 2022-11-26 07:54
Nice fact: creusot is 100x faster than prusti: https://github.com/viperproject/prusti-dev/issues/1243#issuecomment-1326179354

**Comment by xldenis** [comment] 2022-11-28 20:54
>  So, please, tell users to use rust-toolchain file to build creusot

I thought that was unnecessary since this is the default behavior if you use `rustup` 

> So, user should explicitly cd to this repo and then run cargo install --path=.... So, please tell the users this:

Sure, I'll update the build instructions. 

> (Also, if you want, I can report every found issue as a separate bug report.)

Just use your best judgement, no need to split everything down to micro issues but if you feel like an issue is growing beyond the original purview feel free to open a new issue. 

> Nice fact: creusot is 100x faster than prusti: https://github.com/viperproject/prusti-dev/issues/1243#issuecomment-1326179354

An interesting find!

**Closed** 2023-03-13 10:06 UTC
