### ISSUE TITLE
Compiler error on attempted normalizing of generic parameter's ModelTy

### ISSUE THREAD

**Issue by jhaye** [xldenis/creusot#614] opened 2022-10-07 15:10 UTC
I've tried running Creusot on [our sorted vecmap implementation](https://github.com/lf-lang/reactor-rs/blob/main/src/util/vecmap.rs). I've kept things mostly untouched, just imported Creusot's contracts and commented out `Debug`/`Display` impls.

I get the following errors:
```
error[E0277]: the trait bound `K: creusot_contracts::Model` is not satisfied
  --> src/util/vecmap.rs:61:19
   |
61 |             match self.v[i].0.cmp(&key) {
   |                   ^^^^^^^^^^^^^^^^^^^^^ the trait `creusot_contracts::Model` is not implemented for `K`

error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:198:90: Failed to normalize <K as creusot_contracts::Model>::ModelTy, maybe try to call `try_normalize_erasing_regions` instead

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/f83e0266cf7aaa4b41505c49a5fd9c2363166522/compiler/rustc_errors/src/lib.rs:1502:9
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner>::bug::<&alloc::string::String>
   3: <rustc_errors::Handler>::bug::<&alloc::string::String>
   4: rustc_middle::ty::context::tls::with_context_opt::<rustc_middle::ty::context::tls::with_opt<rustc_middle::util::bug::opt_span_bug_fmt<rustc_span::span_encoding::Span>::{closure#0}, ()>::{closure#0}, ()>
   5: rustc_middle::util::bug::opt_span_bug_fmt::<rustc_span::span_encoding::Span>
   6: rustc_middle::util::bug::bug_fmt
   7: <rustc_middle::ty::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder as rustc_middle::ty::fold::TypeFolder>::fold_ty
   8: rustc_middle::ty::normalize_erasing_regions::<impl rustc_middle::ty::context::TyCtxt>::normalize_erasing_regions
   9: creusot::translation::traits::resolve_impl_source_opt
  10: creusot::translation::traits::resolve_assoc_item_opt
  11: creusot::translation::traits::resolve_opt
  12: creusot::clone_map::CloneMap::resolve_dep
  13: creusot::clone_map::CloneMap::to_clones
  14: creusot::translation::function::translate_function
  15: creusot::ctx::TranslationCtx::translate
  16: creusot::translation::after_analysis
  17: rustc_interface::passes::QueryContext::enter
  18: <creusot::callbacks::ToWhy as rustc_driver::Callbacks>::after_expansion
  19: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
  20: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: Creusot has panic-ed!
  |
  = note: Oops, that shouldn't have happened, sorry about that.
  = note: Please report this bug over here: https://github.com/xldenis/creusot/issues/new

query stack during panic:
end of query stack
```

**Comment by xldenis** [comment] 2022-10-07 15:26
The panic is not good, but the error is expected. Check `ord.rs`, you need to implement the relevant trait for those types.

**Comment by xldenis** [comment] 2023-09-28 09:17
I'm going to close this as irreproducible, I know we've changed the relevant parts of the code a lot since this was reported so it's hard to anticipate whether this issue could remain.

**Closed by xldenis** 2023-09-28 09:17 UTC
Labels: bug, error-messages
